[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-GB"
    footer = 'Chaste project'
    alertText = 'Register now: "bring your own project" hackathon, 16-17 September 2026, Oxford, UK. <a class="alert-link stretched-link fw-normal" href="/workshops/2026-09/">Find out more.</a>'
