[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-GB"
    footer = 'Chaste project'
    alertText = 'Save the date: upcoming workshop, 01-03 July 2026, Sheffield, UK. <a class="alert-link stretched-link fw-normal" href="/workshops/2026-07/">Find out more.</a>'
